export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';
export const SET_ORDERS = 'SET_ORDERS';
export const ADD_DETAIL = 'ADD_DETAIL';
export const REMOVE_DETAIL = 'REMOVE_DETAIL';
export const RESET_DETAIL = 'RESET_DETAIL';
export const SHOW_MESSAGE_MODAL = 'SHOW_MESSAGE_MODAL';
export const HIDE_MESSAGE_MODAL = 'HIDE_MESSAGE_MODAL';
